# Generated by Django 5.1.5 on 2025-01-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
        ),
        migrations.AddField(
            model_name="seller",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
