# Generated by Django 5.1.5 on 2025-01-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_friendship_client_name_friendship_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo_prducts",
            field=models.ImageField(blank=True, null=True, upload_to="photo_products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="product_videos/"),
        ),
    ]
