# Generated by Django 5.1.5 on 2025-01-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_productimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
