# Generated by Django 5.1.5 on 2025-01-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_delete_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=1, upload_to="photo_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="product_videos/"),
        ),
    ]
