# Generated by Django 5.1.5 on 2025-01-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_image_product_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="photo_images/"),
        ),
    ]
