# Generated by Django 5.1.4 on 2025-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="facebook",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
