# Generated by Django 5.1.4 on 2025-01-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_seller_facebook_seller_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="facebook",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
