# Generated by Django 5.1.4 on 2025-01-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_seller_facebook_alter_seller_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_whatsapp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
